/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddFooter: typeof import('./components/Footer/AddFooter.vue')['default']
    AddHeader: typeof import('./components/Header/AddHeader.vue')['default']
    ArticlePageHeroSection: typeof import('./components/HeroSection/ArticlePageHeroSection.vue')['default']
    BurgerMenu: typeof import('./components/BurgerMenu/BurgerMenu.vue')['default']
    CreateNewPlaceModal: typeof import('./components/CreateNewPlaceModal/CreateNewPlaceModal.vue')['default']
    CrossIcon: typeof import('./components/icons/CrossIcon.vue')['default']
    DeleteIcon: typeof import('./components/FavoritePlace/DeleteIcon.vue')['default']
    EditIcon: typeof import('./components/FavoritePlace/EditIcon.vue')['default']
    FavoritePlace: typeof import('./components/FavoritePlace/FavoritePlace.vue')['default']
    FavoritePlaceIconButton: typeof import('./components/FavoritePlace/FavoritePlaceIconButton.vue')['default']
    FavoritePlaces: typeof import('./components/FavoritePlaces/FavoritePlaces.vue')['default']
    FiltrButton: typeof import('./components/FiltrButton/FiltrButton.vue')['default']
    FormContainer: typeof import('./components/Auth/FormContainer.vue')['default']
    GridCard: typeof import('./components/GridCard/GridCard.vue')['default']
    Header: typeof import('./components/Header/Header.vue')['default']
    HeaderSupportButton: typeof import('./components/SupportButton/HeaderSupportButton.vue')['default']
    HeroSection: typeof import('./components/HeroSection/HeroSection.vue')['default']
    IButton: typeof import('./components/IButton/IButton.vue')['default']
    IInput: typeof import('./components/IInput/IInput.vue')['default']
    IModal: typeof import('./components/IModal/IModal.vue')['default']
    InputImage: typeof import('./components/InputImage/InputImage.vue')['default']
    LoginForm: typeof import('./components/Auth/LoginForm/LoginForm.vue')['default']
    LogoButton: typeof import('./components/LogoButton/LogoButton.vue')['default']
    MarkerIcon: typeof import('./components/icons/MarkerIcon.vue')['default']
    RegistrationForm: typeof import('./components/Auth/RegistrationForm/RegistrationForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StartPageGrid: typeof import('./components/StartPageGrid/StartPageGrid.vue')['default']
    StartPageHeroSection: typeof import('./components/HeroSection/StartPageHeroSection.vue')['default']
    SupportButton: typeof import('./components/SupportButton/SupportButton.vue')['default']
    UploadIcon: typeof import('./components/InputImage/UploadIcon.vue')['default']
  }
}
